// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCviKOKTkzWq2fbbSGttrfTNkgIogNvPzI',
    appId: '1:555516586586:web:3e24d79fa838a532514663',
    messagingSenderId: '555516586586',
    projectId: 'gdahospital-344a8',
    authDomain: 'gdahospital-344a8.firebaseapp.com',
    storageBucket: 'gdahospital-344a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRfM09ke2DZySaEYj3SZdlNqqbDrjE1tc',
    appId: '1:555516586586:android:d16d5bf23b07f252514663',
    messagingSenderId: '555516586586',
    projectId: 'gdahospital-344a8',
    storageBucket: 'gdahospital-344a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdxfroHACPKSYT-QYLOLcs1ZLDJzKvJs',
    appId: '1:555516586586:ios:0d0a1d648275a853514663',
    messagingSenderId: '555516586586',
    projectId: 'gdahospital-344a8',
    storageBucket: 'gdahospital-344a8.appspot.com',
    iosClientId: '555516586586-2ehl5jpgr7be0842mcfi3dlkdj14ri46.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdahospital',
  );
}
